In [ ]:
import pandas as pd

In [26]:
df_feature = pd.read_excel('../data/train/sample_1/Feature-02-shahidi_english.xlsx')
df_edge = pd.read_excel('../data/train/sample_1/Edge-02-shahidi.xlsx')
df_label = pd.read_excel('../data/train/sample_1/Label-02-shahidi.xlsx')

In [27]:
df_feature.head()

,Element_Name,Structural_System,Opening_Status,Height_Difference,Roof_Area_Difference_Excluding_Roof,Relative_to_Horizontal_Axis,Relative_to_Vertical_Axis,Beam_Arrangement,Width_to_Length_Ratio,Number_of_Horizontal_Frames,...,EX,EY,CMX,CRX,DeltaX,CMY,CRY,DeltaY,CRXi,CRYi
0,1,0,0,0,0,0,0,1,0.901,3,...,0.00,0.00,788.246,676.522,111.724,1133.950,1261.156,127.206,676.522,-283.844
1,2,0,0,0,0,0,0,1,0.901,3,...,0.00,-1283.77,784.329,671.362,112.967,1125.559,1266.514,140.955,671.362,-278.486
2,3,0,0,0,0,0,0,1,0.901,3,...,4279.22,1283.77,784.329,665.178,119.151,1125.559,1269.956,144.397,665.178,-275.044
3,4,0,0,0,0,0,0,1,0.901,3,...,-4279.22,-1283.77,784.329,659.083,125.246,1125.559,1269.610,144.051,659.083,-275.390
4,5,0,0,0,0,0,0,1,0.901,3,...,-4279.22,1283.77,784.329,652.063,132.266,1125.559,1264.814,139.255,652.063,-280.186

In [28]:
df_feature.columns

Index(['Element_Name', 'Structural_System', 'Opening_Status',
       'Height_Difference', 'Roof_Area_Difference_Excluding_Roof',
       'Relative_to_Horizontal_Axis', 'Relative_to_Vertical_Axis',
       'Beam_Arrangement', 'Width_to_Length_Ratio',
       'Number_of_Horizontal_Frames', 'Number_of_Vertical_Frames',
       'Frame_Ratio_X_to_Y', 'Structure_Height', 'Number_of_Floors',
       'Earthquake_Coefficient', 'Allowable_Drift',
       'Beam_Concrete_Compressive_Strength',
       'Column_Concrete_Compressive_Strength', 'Dynamic_Analysis',
       'Static_Analysis', 'X1', 'Y1', 'Z1', 'X2', 'Y2', 'Z2', 'Length',
       'Angle', 'Story', 'Ele_Type', 'Boundary', 'Alignment', 'GravityForce',
       'EX', 'EY', 'CMX', 'CRX', 'DeltaX', 'CMY', 'CRY', 'DeltaY', 'CRXi',
       'CRYi'],
      dtype='object')

In [29]:
df_edge.head()

   Source  Target
0      16      17
1      17      16
2      16     161
3     161      16
4      16     185

In [31]:
df_edge.columns

Index(['Source', 'Target'], dtype='object')

In [30]:
df_label.head()

   Element Name  Width (b)  Height (h)
0             1         50          50
1             2         50          50
2             3         50          50
3             4         50          50
4             5         55          55

In [32]:
df_label.columns

Index(['Element Name', 'Width (b)', 'Height (h)'], dtype='object')